language: python
python:
  - 2.7
  - 3.6
install:
  - pip install tox-travis
  - pip install pytest-cov coveralls
script: tox
after_success: coveralls
notifications:
  email:
    on_success: never
    on_failure: always
